[package]
name = "RMail"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.47", features = ["derive"] }
directories = "6.0.0"
imap = "2.4.1"
keyring = { version = "3.6.3", default-features = false, features = ["apple-native", "windows-native", "sync-secret-service"] }
lettre = { version = "0.11.23", default-features = false, features = ["builder", "smtp-transport", "rustls", "ring", "webpki-roots"] }
mail-parser = "0.11.6"
mime_guess = "2.0.5"
native-tls = "0.2.14"
rand = "0.8.5"
rpassword = "7.4.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
toml = "0.9.5"
uuid = { version = "1.18.1", features = ["v4"] }
zeroize = { version = "1.8.1", features = ["serde"] }

[dev-dependencies]
tempfile = "3.23.0"
